# Generated by Django 4.2.5 on 2023-11-29 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banche',
            fields=[
                ('codban', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desban', models.CharField(max_length=40, unique=True)),
                ('codabi', models.CharField(max_length=5)),
                ('codcab', models.CharField(max_length=5)),
                ('codsia', models.CharField(max_length=5)),
                ('iban', models.CharField(max_length=27)),
                ('bic', models.CharField(max_length=11)),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'banche',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Catego',
            fields=[
                ('codcat', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descat', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'catego',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('codcli', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ragsoc', models.CharField(max_length=40)),
                ('datagg', models.CharField(max_length=40)),
                ('indiri', models.CharField(max_length=40)),
                ('locali', models.CharField(max_length=30)),
                ('provin', models.CharField(max_length=2)),
                ('cap', models.CharField(max_length=5)),
                ('rssped', models.CharField(max_length=40)),
                ('dasped', models.CharField(max_length=40)),
                ('insped', models.CharField(max_length=40)),
                ('losped', models.CharField(max_length=30)),
                ('prsped', models.CharField(max_length=2)),
                ('capspe', models.CharField(max_length=5)),
                ('telefo', models.CharField(max_length=15)),
                ('cellul', models.CharField(max_length=15)),
                ('telef1', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('pec', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=40)),
                ('sito', models.CharField(max_length=40)),
                ('codfis', models.CharField(max_length=16)),
                ('pariva', models.CharField(max_length=20)),
                ('banapp', models.CharField(max_length=40)),
                ('fido', models.IntegerField()),
                ('sconto', models.IntegerField()),
                ('codcab', models.CharField(max_length=5)),
                ('codabi', models.CharField(max_length=5)),
                ('paese', models.CharField(max_length=2)),
                ('cineur', models.CharField(max_length=2)),
                ('cin', models.CharField(max_length=1)),
                ('conto', models.CharField(max_length=12)),
                ('chiusf', models.DateField()),
                ('chiust', models.DateField()),
                ('nome', models.CharField(max_length=30)),
                ('spese', models.BooleanField(default=False)),
                ('storic', models.BooleanField(default=False)),
                ('staest', models.CharField(max_length=3)),
                ('tipfor', models.IntegerField()),
                ('alias', models.CharField(max_length=40)),
                ('spesom', models.BooleanField(default=False)),
                ('fatema', models.BooleanField(default=False)),
                ('impass', models.IntegerField()),
                ('annass', models.CharField(max_length=4)),
                ('coduni', models.CharField(max_length=7)),
                ('splpay', models.CharField(max_length=1)),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('codban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.banche')),
                ('codcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.catego')),
            ],
            options={
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('codzon', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('deszon', models.CharField(max_length=40, unique=True)),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'zone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('codval', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desval', models.CharField(max_length=50)),
                ('simval', models.CharField(max_length=2)),
                ('valcam', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'valute',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nazion',
            fields=[
                ('codnaz', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('desnaz', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'nazion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modpag',
            fields=[
                ('codpag', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('despag', models.CharField(max_length=40, unique=True)),
                ('tippag', models.CharField(max_length=40)),
                ('numrat', models.CharField(max_length=3)),
                ('giosca', models.CharField(max_length=3)),
                ('period', models.CharField(max_length=3)),
                ('tipsca', models.CharField(max_length=40)),
                ('escmes', models.CharField(max_length=40)),
                ('scocas', models.CharField(max_length=5)),
                ('gifisc', models.CharField(max_length=3)),
                ('modpag', models.CharField(max_length=11)),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'modpag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ivaven',
            fields=[
                ('codiva', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('desiva', models.CharField(max_length=20)),
                ('aliquo', models.FloatField()),
                ('indagg', models.CharField(max_length=1)),
                ('natura', models.CharField(max_length=2)),
                ('esclip', models.BooleanField()),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'ivaven',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eseiva',
            fields=[
                ('codese', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('riccli', models.CharField(max_length=4)),
                ('datric', models.DateField()),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'eseiva',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Destcl',
            fields=[
                ('codest', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dedest', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('codcli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'destcl',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='codese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.eseiva'),
        ),
        migrations.AddField(
            model_name='client',
            name='codiva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.ivaven'),
        ),
        migrations.AddField(
            model_name='client',
            name='codnaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.nazion'),
        ),
        migrations.AddField(
            model_name='client',
            name='codpag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.modpag'),
        ),
        migrations.AddField(
            model_name='client',
            name='codval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.valute'),
        ),
        migrations.AddField(
            model_name='client',
            name='codzon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.zone'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.CreateModel(
            name='Aspest',
            fields=[
                ('codasp', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desasp', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'aspest',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Artico',
            fields=[
                ('codart', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desart', models.CharField(max_length=40)),
                ('prezzo', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'artico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Agenti',
            fields=[
                ('codage', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desage', models.CharField(max_length=40)),
                ('provvi', models.CharField(max_length=5)),
                ('date_created', models.DateTimeField(default='2023-11-29 16:58:04')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'agenti',
                'managed': True,
            },
        ),
    ]
