# Generated by Django 4.2.5 on 2023-10-27 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banche',
            fields=[
                ('codban', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desban', models.CharField(max_length=40, unique=True)),
                ('codabi', models.CharField(max_length=5)),
                ('codcab', models.CharField(max_length=5)),
                ('codsia', models.CharField(max_length=5)),
                ('iban', models.CharField(max_length=27)),
                ('bic', models.CharField(max_length=11)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
