# Generated by Django 4.2.5 on 2023-12-21 14:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artico',
            fields=[
                ('codart', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desart', models.CharField(max_length=40)),
                ('prezzo', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'artico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Banche',
            fields=[
                ('codban', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desban', models.CharField(max_length=40, unique=True)),
                ('codabi', models.CharField(max_length=5)),
                ('codcab', models.CharField(max_length=5)),
                ('codsia', models.CharField(max_length=5)),
                ('iban', models.CharField(max_length=27)),
                ('bic', models.CharField(max_length=11)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'banche',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Catego',
            fields=[
                ('codcat', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descat', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'catego',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('codcli', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ragsoc', models.CharField(max_length=40)),
                ('datagg', models.CharField(max_length=40)),
                ('indiri', models.CharField(max_length=40)),
                ('locali', models.CharField(max_length=30)),
                ('provin', models.CharField(max_length=2)),
                ('cap', models.CharField(max_length=5)),
                ('rssped', models.CharField(max_length=40)),
                ('dasped', models.CharField(max_length=40)),
                ('insped', models.CharField(max_length=40)),
                ('losped', models.CharField(max_length=30)),
                ('prsped', models.CharField(max_length=2)),
                ('capspe', models.CharField(max_length=5)),
                ('telefo', models.CharField(max_length=15)),
                ('cellul', models.CharField(max_length=15)),
                ('telef1', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('pec', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=40)),
                ('sito', models.CharField(max_length=40)),
                ('codfis', models.CharField(max_length=16)),
                ('pariva', models.CharField(max_length=20)),
                ('banapp', models.CharField(max_length=40)),
                ('fido', models.IntegerField()),
                ('sconto', models.IntegerField()),
                ('codcab', models.CharField(max_length=5)),
                ('codabi', models.CharField(max_length=5)),
                ('paese', models.CharField(max_length=2)),
                ('cineur', models.CharField(max_length=2)),
                ('cin', models.CharField(max_length=1)),
                ('conto', models.CharField(max_length=12)),
                ('chiusf', models.DateField()),
                ('chiust', models.DateField()),
                ('nome', models.CharField(max_length=30)),
                ('spese', models.BooleanField(default=False)),
                ('storic', models.BooleanField(default=False)),
                ('staest', models.CharField(max_length=3)),
                ('tipfor', models.IntegerField()),
                ('alias', models.CharField(max_length=40)),
                ('spesom', models.BooleanField(default=False)),
                ('fatema', models.BooleanField(default=False)),
                ('impass', models.IntegerField()),
                ('annass', models.CharField(max_length=4)),
                ('coduni', models.CharField(max_length=7)),
                ('splpay', models.CharField(max_length=1)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('codban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.banche')),
                ('codcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.catego')),
            ],
            options={
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Conabi',
            fields=[
                ('codcon', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descon', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'conabi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('codzon', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('deszon', models.CharField(max_length=40, unique=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'zone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('codval', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desval', models.CharField(max_length=50)),
                ('simval', models.CharField(max_length=2)),
                ('valcam', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'valute',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipall',
            fields=[
                ('codtal', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('destal', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'tipall',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Spediz',
            fields=[
                ('codspe', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desspe', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'spediz',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Raggfi',
            fields=[
                ('codrag', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desrag', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'raggfi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Porto',
            fields=[
                ('codpor', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('despor', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'porto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Piacon',
            fields=[
                ('codpia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('despia', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('codcon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataManager.conabi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'piacon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nazion',
            fields=[
                ('codnaz', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('desnaz', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'nazion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modpag',
            fields=[
                ('codpag', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('despag', models.CharField(max_length=40, unique=True)),
                ('tippag', models.CharField(max_length=40)),
                ('numrat', models.CharField(max_length=3)),
                ('giosca', models.CharField(max_length=3)),
                ('period', models.CharField(max_length=3)),
                ('tipsca', models.CharField(max_length=40)),
                ('escmes', models.CharField(max_length=40)),
                ('scocas', models.CharField(max_length=5)),
                ('gifisc', models.CharField(max_length=3)),
                ('modpag', models.CharField(max_length=11)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'modpag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Liscli',
            fields=[
                ('prezzo', models.CharField(max_length=13)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('codart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.artico')),
                ('codcli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'liscli',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ivaven',
            fields=[
                ('codiva', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('desiva', models.CharField(max_length=20)),
                ('aliquo', models.FloatField()),
                ('indagg', models.CharField(max_length=1)),
                ('natura', models.CharField(max_length=2)),
                ('esclip', models.BooleanField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'ivaven',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ivacor',
            fields=[
                ('codiva', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('desiva', models.CharField(max_length=20)),
                ('aliquo', models.FloatField()),
                ('natura', models.CharField(max_length=2)),
                ('esclip', models.BooleanField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'ivacor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ivaacq',
            fields=[
                ('codiva', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('desiva', models.CharField(max_length=20)),
                ('aliquo', models.FloatField()),
                ('indetr', models.CharField(max_length=3)),
                ('indagg', models.CharField(max_length=1)),
                ('natura', models.CharField(max_length=2)),
                ('esclip', models.BooleanField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'ivaacq',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fornit',
            fields=[
                ('ragsoc', models.CharField(max_length=40, unique=True)),
                ('datagg', models.CharField(max_length=40)),
                ('indiri', models.CharField(max_length=40)),
                ('locali', models.CharField(max_length=30)),
                ('provin', models.CharField(max_length=2)),
                ('cap', models.CharField(max_length=5)),
                ('codfis', models.CharField(max_length=5)),
                ('pariva', models.CharField(max_length=15)),
                ('telef1', models.CharField(max_length=15)),
                ('telef2', models.CharField(max_length=15)),
                ('cellul', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40)),
                ('codfor', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('sito', models.CharField(max_length=40)),
                ('pae', models.CharField(max_length=2)),
                ('cineur', models.CharField(max_length=2)),
                ('cin', models.CharField(max_length=1)),
                ('conto', models.CharField(max_length=12)),
                ('codabi', models.CharField(max_length=5)),
                ('codcab', models.CharField(max_length=5)),
                ('banapp', models.CharField(max_length=40)),
                ('storic', models.BooleanField()),
                ('staest', models.CharField(max_length=3)),
                ('tipfor', models.IntegerField()),
                ('spesom', models.BooleanField()),
                ('schcar', models.BooleanField()),
                ('alias', models.CharField(max_length=24)),
                ('regfis', models.CharField(max_length=4)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('codban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.banche')),
                ('codcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.catego')),
                ('codiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.ivaacq')),
                ('codnaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.nazion')),
                ('codpag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.modpag')),
                ('codzon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.zone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'fornit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eseiva',
            fields=[
                ('codese', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('riccli', models.CharField(max_length=4)),
                ('datric', models.DateField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'eseiva',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dipend',
            fields=[
                ('coddip', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('assunt', models.CharField(max_length=2)),
                ('tiptar', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'dipend',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Destfo',
            fields=[
                ('codest', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dedest', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('codfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.fornit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'destfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Destcl',
            fields=[
                ('codest', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dedest', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('codcli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'destcl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Degrar',
            fields=[
                ('codgar', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desgar', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'degrar',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='codese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.eseiva'),
        ),
        migrations.AddField(
            model_name='client',
            name='codiva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.ivaven'),
        ),
        migrations.AddField(
            model_name='client',
            name='codnaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.nazion'),
        ),
        migrations.AddField(
            model_name='client',
            name='codpag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.modpag'),
        ),
        migrations.AddField(
            model_name='client',
            name='codval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.valute'),
        ),
        migrations.AddField(
            model_name='client',
            name='codzon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.zone'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.CreateModel(
            name='Cenlav',
            fields=[
                ('codcen', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descen', models.CharField(max_length=40, unique=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'cenlav',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cautra',
            fields=[
                ('codcau', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descau', models.CharField(max_length=50)),
                ('stafat', models.CharField(max_length=1)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'cautra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Catcon',
            fields=[
                ('codcat', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descat', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('codpia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.piacon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'catcon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Aspest',
            fields=[
                ('codasp', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desasp', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'aspest',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Agenti',
            fields=[
                ('codage', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('desage', models.CharField(max_length=40)),
                ('provvi', models.CharField(max_length=5)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 2, 29), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'agenti',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='liscli',
            constraint=models.UniqueConstraint(fields=('codart', 'codcli'), name='liscli_sk'),
        ),
    ]
