# Generated by Django 4.2.5 on 2023-10-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banche',
            table='banche',
        ),
    ]
