# Generated by Django 4.2.5 on 2024-01-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banche',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
