# Generated by Django 4.2.5 on 2024-01-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManager', '0002_alter_banche_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='banche',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='banche',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
