# Generated by Django 4.2.5 on 2024-01-21 15:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DataManager', '0005_alter_agenti_date_created_alter_artico_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenti',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='artico',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='artico',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aspest',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='banche',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='catcon',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='catego',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='cautra',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='cenlav',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='conabi',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='degrar',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='destcl',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='destfo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='dipend',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='eseiva',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='fornit',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='ivaacq',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='ivacor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='ivaven',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='liscli',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='modpag',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='nazion',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='piacon',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='porto',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='raggfi',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='spediz',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='tipall',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='valute',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.AlterField(
            model_name='zone',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False),
        ),
        migrations.CreateModel(
            name='Scacli',
            fields=[
                ('numpro', models.AutoField(primary_key=True, serialize=False)),
                ('tipdoc', models.CharField(max_length=1)),
                ('datdoc', models.DateTimeField()),
                ('numfat', models.CharField(max_length=5)),
                ('descri', models.CharField(max_length=35)),
                ('impfat', models.DecimalField(decimal_places=2, max_digits=11)),
                ('imppag', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cambio', models.DecimalField(decimal_places=3, max_digits=11)),
                ('datsca', models.DateTimeField()),
                ('pagato', models.CharField(max_length=1)),
                ('tippag', models.CharField(max_length=1)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 8, 51), editable=False)),
                ('codban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.banche')),
                ('codcli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.client')),
                ('codpag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.modpag')),
                ('codval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.valute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'scaden',
                'managed': True,
            },
        ),
    ]
