# Generated by Django 4.2.5 on 2023-12-08 15:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DataManager', '0018_alter_agenti_date_created_alter_artico_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenti',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='artico',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='aspest',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='banche',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='catcon',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='catego',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='cautra',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='cenlav',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='conabi',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='degrar',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='destcl',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='dipend',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='eseiva',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='ivaven',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='modpag',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='nazion',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='piacon',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='valute',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.AlterField(
            model_name='zone',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False),
        ),
        migrations.CreateModel(
            name='Ivaacq',
            fields=[
                ('codiva', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('desiva', models.CharField(max_length=20)),
                ('aliquo', models.FloatField()),
                ('indetr', models.CharField(max_length=3)),
                ('indagg', models.CharField(max_length=1)),
                ('natura', models.CharField(max_length=2)),
                ('esclip', models.BooleanField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'ivaacq',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fornit',
            fields=[
                ('ragsoc', models.CharField(max_length=40, unique=True)),
                ('datagg', models.CharField(max_length=40)),
                ('indiri', models.CharField(max_length=40)),
                ('locali', models.CharField(max_length=30)),
                ('provin', models.CharField(max_length=2)),
                ('cap', models.CharField(max_length=5)),
                ('codfis', models.CharField(max_length=5)),
                ('pariva', models.CharField(max_length=15)),
                ('telef1', models.CharField(max_length=15)),
                ('telef2', models.CharField(max_length=15)),
                ('cellul', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40)),
                ('codfor', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('sito', models.CharField(max_length=40)),
                ('pae', models.CharField(max_length=2)),
                ('cineur', models.CharField(max_length=2)),
                ('cin', models.CharField(max_length=1)),
                ('conto', models.CharField(max_length=12)),
                ('codabi', models.CharField(max_length=5)),
                ('codcab', models.CharField(max_length=5)),
                ('banapp', models.CharField(max_length=40)),
                ('storic', models.BooleanField()),
                ('staest', models.CharField(max_length=3)),
                ('tipfor', models.IntegerField()),
                ('spesom', models.BooleanField()),
                ('schcar', models.BooleanField()),
                ('alias', models.CharField(max_length=24)),
                ('regfis', models.CharField(max_length=4)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 59, 7), editable=False)),
                ('codban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.banche')),
                ('codcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.catego')),
                ('codiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.ivaacq')),
                ('codnaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.nazion')),
                ('codpag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.modpag')),
                ('codzon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.zone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'fornit',
                'managed': True,
            },
        ),
    ]
