# Generated by Django 4.2.5 on 2023-12-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='background_image',
            new_name='bg_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='background_color',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bg_color',
            field=models.CharField(default='#c8d4fd', help_text='Hexadecimal background color', max_length=7),
        ),
    ]
