# Generated by Django 4.2.5 on 2023-12-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_rename_background_image_customuser_bg_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bg_color',
            field=models.CharField(blank=True, help_text='Hexadecimal background color', max_length=7, null=True),
        ),
    ]
