# Generated by Django 4.2.5 on 2023-12-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_customuser_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_resize',
            field=models.BooleanField(default=False),
        ),
    ]
