# Generated by Django 4.2.5 on 2024-01-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_customuser_image_resize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bg_color',
            field=models.CharField(blank=True, default='#c8d4fd', help_text='Hexadecimal background color', max_length=7, null=True),
        ),
    ]
