from django.db import models
from Login.models import CustomUser
from .ivaven import Ivaven
from .ivaacq import Ivaacq
from .piacon import Piacon

class Ragsoc(models.Model):
    datini = models.DateField(primary_key=True)
    ragsoc = models.CharField(max_length=50)
    indiri = models.CharField(max_length=50, null=True, blank=True)
    locali = models.CharField(max_length=50, null=True, blank=True)
    cap = models.CharField(max_length=5, null=True, blank=True)
    provin = models.CharField(max_length=2, null=True, blank=True)
    pariva = models.CharField(max_length=11)
    codfis = models.CharField(max_length=16, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    sito = models.CharField(max_length=50, null=True, blank=True)
    corven = models.ForeignKey(Ivaven, to_field='codiva', on_delete=models.CASCADE, null=True, blank=True)
    art10 = models.ForeignKey(Ivaacq, to_field='codiva', on_delete=models.CASCADE, null=True, blank=True)
    ditind = models.BooleanField()
    sesso = models.CharField(max_length=1, null=True, blank=True)
    datnas = models.DateField(null=True, blank=True)
    comnas = models.CharField(max_length=50, null=True, blank=True)
    pronas = models.CharField(max_length=2, null=True, blank=True)
    cognom = models.CharField(max_length=50, null=True, blank=True)
    nome = models.CharField(max_length=50, null=True, blank=True)
    tipsog = models.CharField(max_length=2)
    tipcon = models.CharField(max_length=1)
    tipiva = models.CharField(max_length=1)
    banapp = models.CharField(max_length=50, null=True, blank=True)
    iban = models.CharField(max_length=27, null=True, blank=True)
    cofiin = models.CharField(max_length=16, null=True, blank=True)
    iscain = models.CharField(max_length=5, null=True, blank=True)
    compre = models.CharField(max_length=1, null=True, blank=True)
    cofiso = models.CharField(max_length=16, null=True, blank=True)
    codatt = models.CharField(max_length=6, null=True, blank=True)
    gescor = models.BooleanField()
    regfis = models.CharField(max_length=2)
    isrepr = models.CharField(max_length=2, null=True, blank=True)
    isrenu = models.CharField(max_length=6, null=True, blank=True)
    capsoc = models.DecimalField(max_digits=10, decimal_places=2)
    socuni = models.CharField(max_length=2, null=True, blank=True)
    staliq = models.CharField(max_length=2, null=True, blank=True)

    maclit = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='maclit')
    macles = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='macles')
    masfor = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='masfor')
    ivcove = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='ivcove')
    ivcoac = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='ivcoac')
    ivcoco = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='ivcoco')
    cassa  = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='cassa')
    cotrri = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='cotrri')
    spetra = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='spetra')
    spebol = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='spebol')
    speinc = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='speinc')
    picfat = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='picfat')
    portra = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='portra')
    poriba = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='poriba')
    conven = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='conven')
    copapa = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='copapa')
    ivacce = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='ivacce')
    ivvece = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='ivvece')
    ivacre = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='ivacre')
    ivvere = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='ivvere')
    coriac = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='coriac')
    conena = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='conena')
    cocoin = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='cocoin')
    ivvesp = models.ForeignKey(Piacon, to_field='codpia', on_delete=models.CASCADE, null=True, blank=True, related_name='ivvesp')
    
    coivtr = models.ForeignKey(Ivaven, to_field='codiva', on_delete=models.CASCADE, null=True, blank=True, related_name='coivtr')
    coivbo = models.ForeignKey(Ivaven, to_field='codiva', on_delete=models.CASCADE, null=True, blank=True, related_name='coivbo')
    coivin = models.ForeignKey(Ivaven, to_field='codiva', on_delete=models.CASCADE, null=True, blank=True, related_name='coivin')
    coivpi = models.ForeignKey(Ivaven, to_field='codiva', on_delete=models.CASCADE, null=True, blank=True, related_name='coivpi')
    coivta = models.ForeignKey(Ivaven, to_field='codiva', on_delete=models.CASCADE, null=True, blank=True, related_name='coivta')
    coivri = models.ForeignKey(Ivaven, to_field='codiva', on_delete=models.CASCADE, null=True, blank=True, related_name='coivri')

    ritenu = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    imponi = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    enasar = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    ritena = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    impena = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    user = models.ForeignKey(CustomUser, to_field='username', on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        managed = True
        db_table = 'ragsoc'